python main.py split --net acasxu_test_iter1.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter2.onnx
python main.py split --net acasxu_test_iter2.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter3.onnx
python main.py split --net acasxu_test_iter3.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter4.onnx
python main.py split --net acasxu_test_iter4.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter5.onnx
python main.py split --net acasxu_test_iter5.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter6.onnx
python main.py split --net acasxu_test_iter6.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter7.onnx
python main.py split --net acasxu_test_iter7.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter8.onnx
python main.py split --net acasxu_test_iter8.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter9.onnx
python main.py split --net acasxu_test_iter9.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter10.onnx
python main.py split --net acasxu_test_iter10.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter11.onnx
python main.py split --net acasxu_test_iter11.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter12.onnx
python main.py split --net acasxu_test_iter12.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter13.onnx
python main.py split --net acasxu_test_iter13.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter14.onnx
python main.py split --net acasxu_test_iter14.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter15.onnx
python main.py split --net acasxu_test_iter15.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter16.onnx
python main.py split --net acasxu_test_iter16.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter17.onnx
python main.py split --net acasxu_test_iter17.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter18.onnx
python main.py split --net acasxu_test_iter18.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter19.onnx
python main.py split --net acasxu_test_iter19.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter20.onnx
python main.py split --net acasxu_test_iter20.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter21.onnx
python main.py split --net acasxu_test_iter21.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter22.onnx
python main.py split --net acasxu_test_iter22.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter23.onnx
python main.py split --net acasxu_test_iter23.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter24.onnx
python main.py split --net acasxu_test_iter24.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter25.onnx
python main.py split --net acasxu_test_iter25.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter26.onnx
python main.py split --net acasxu_test_iter26.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter27.onnx
python main.py split --net acasxu_test_iter27.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter28.onnx
python main.py split --net acasxu_test_iter28.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter29.onnx
python main.py split --net acasxu_test_iter29.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter30.onnx
python main.py split --net acasxu_test_iter30.onnx --spec data/acasxu/vnnlib/prop_1.vnnlib --seed 0 --output acasxu_test_iter31.onnx
